replicaCount: 1

image:
  repository: amithauzer/amitchart-phase3-flask
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 5000

livenessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: 5000
  initialDelaySeconds: 5
  periodSeconds: 10

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

ingress:
  enabled: false

autoscaling:
  enabled: false
