name: Install uv and sync dependencies
description: Installs uv and syncs dependencies
runs:
  using: "composite"
  steps:
    - run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv sync --dev
      shell: bash
