apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-phase-3
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/AmitHauzer/helm-phase-3"
    targetRevision: main
    path: amitchart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
